services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: apps/api/Dockerfile
  #   ports:
  #     - 3333:3333
  #   depends_on:
  #     - postgres

  # web:
  #   build:
  #     context: .
  #     dockerfile: apps/web/Dockerfile
  #   ports:
  #     - 3000:3000
  #   environment:
  #     NEXT_CONFIG_OUTPUT: standalone
  #   depends_on:
  #     - postgres

  postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: db-better-chat
    volumes:
      - postgres-data:/bitnami/postgresql

volumes:
  postgres-data:
