services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: apps/api/Dockerfile
  #   ports:
  #     - 3333:3333
  #   env_file:
  #     - .env

  # web:
  #   build:
  #     context: .
  #     dockerfile: apps/web/Dockerfile
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env
  #   depends_on:
  #     - api

  postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: db-better-chat
    volumes:
      - postgres-data:/bitnami/postgresql

  redis:
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - redis-data:/bitnami/redis/data

volumes:
  postgres-data:
  redis-data:
