import { env as databaseEnv } from '@workspace/db/env'
import { createEnv, z } from '@workspace/env'

export const env = createEnv({
  extends: [databaseEnv],
  server: {
    STRIPE_SECRET_KEY: z.string(),
    STRIPE_WEBHOOK_SECRET: z.string(),

    // STRIPE_PLUS_PLAN_PRICE_ID: z.string(),
    // STRIPE_PLUS_PLAN_AI_USAGE_PRICE_ID: z.string(),

    STRIPE_HOBBY_PLAN_PRICE_ID: z.string(),
    STRIPE_HOBBY_PLAN_AI_USAGE_PRICE_ID: z.string(),
    STRIPE_HOBBY_PLAN_COMPUTE_USAGE_PRICE_ID: z.string(),

    STRIPE_STANDARD_PLAN_PRICE_ID: z.string(),
    STRIPE_STANDARD_PLAN_AI_USAGE_PRICE_ID: z.string(),
    STRIPE_STANDARD_PLAN_COMPUTE_USAGE_PRICE_ID: z.string(),

    STRIPE_ADVANCED_PLAN_PRICE_ID: z.string(),
    STRIPE_ADVANCED_PLAN_AI_USAGE_PRICE_ID: z.string(),
    STRIPE_ADVANCED_PLAN_COMPUTE_USAGE_PRICE_ID: z.string(),

    STRIPE_AI_USAGE_METER_ID: z.string(),
    STRIPE_COMPUTE_USAGE_METER_ID: z.string(),

    CURRENCY_API_KEY: z.string().optional(),
  },
  runtimeEnv: {
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,

    // STRIPE_PLUS_PLAN_PRICE_ID: process.env.STRIPE_PLUS_PLAN_PRICE_ID,
    // STRIPE_PLUS_PLAN_AI_USAGE_PRICE_ID: process.env.STRIPE_PLUS_PLAN_AI_USAGE_PRICE_ID,

    STRIPE_HOBBY_PLAN_PRICE_ID: process.env.STRIPE_HOBBY_PLAN_PRICE_ID,
    STRIPE_HOBBY_PLAN_AI_USAGE_PRICE_ID:
      process.env.STRIPE_HOBBY_PLAN_AI_USAGE_PRICE_ID,
    STRIPE_HOBBY_PLAN_COMPUTE_USAGE_PRICE_ID:
      process.env.STRIPE_HOBBY_PLAN_COMPUTE_USAGE_PRICE_ID,

    STRIPE_STANDARD_PLAN_PRICE_ID: process.env.STRIPE_STANDARD_PLAN_PRICE_ID,
    STRIPE_STANDARD_PLAN_AI_USAGE_PRICE_ID:
      process.env.STRIPE_STANDARD_PLAN_AI_USAGE_PRICE_ID,
    STRIPE_STANDARD_PLAN_COMPUTE_USAGE_PRICE_ID:
      process.env.STRIPE_STANDARD_PLAN_COMPUTE_USAGE_PRICE_ID,

    STRIPE_ADVANCED_PLAN_PRICE_ID: process.env.STRIPE_ADVANCED_PLAN_PRICE_ID,
    STRIPE_ADVANCED_PLAN_AI_USAGE_PRICE_ID:
      process.env.STRIPE_ADVANCED_PLAN_AI_USAGE_PRICE_ID,
    STRIPE_ADVANCED_PLAN_COMPUTE_USAGE_PRICE_ID:
      process.env.STRIPE_ADVANCED_PLAN_COMPUTE_USAGE_PRICE_ID,

    STRIPE_AI_USAGE_METER_ID: process.env.STRIPE_AI_USAGE_METER_ID,
    STRIPE_COMPUTE_USAGE_METER_ID: process.env.STRIPE_COMPUTE_USAGE_METER_ID,

    CURRENCY_API_KEY: process.env.CURRENCY_API_KEY,
  },
  emptyStringAsUndefined: true,
  skipValidation: !!process.env.CI,
})
